class RobotAgent:
    # ====== Agente ======
    def agent(self, rules: list, listen_duration: float = 3.0, camera_name: str = "top") -> None: ...

    # ====== Câmeras ======
    def show_camera(self, camera_name: str = "top") -> None: ...
    def show_camera_stream(self, camera_name: str = "top", duration: int = 10) -> None: ...
    def test_camera_info(self) -> None: ...
    def get_camera_frame(self, camera_name: str = "top"): ...
    def is_person_in_room(self, camera_name: str = "top") -> bool: ...
    def is_object_in_frame(self, object_name: str, camera_name: str = "top") -> bool: ...

    # ====== LEDs ======
    def set_led(self, name: str, color: str, duration: float = 1.0) -> None: ...
    def off_led(self, name: str) -> None: ...
    def eye_color(self, color: str) -> bool: ...
    def chest_color(self, color: str) -> bool: ...
    def ear_color(self, ear: str, color: str) -> bool: ...
    def blink_eyes(self, times: int = 3, duration: float = 0.5) -> bool: ...
    def rainbow_eyes(self, duration: float = 5.0) -> bool: ...

    # ====== Áudio ======
    def listen(self, duration: float = 5.0, extra_vocabulary=None) -> list: ...

    # ====== Face & rastreamento ======
    def start_face_tracking(self) -> bool: ...
    def stop_face_tracking(self) -> bool: ...
    def detect_faces(self) -> list: ...
    def track_red_ball(self) -> bool: ...

    # ====== Sensores ======
    def get_battery_level(self) -> float: ...
    def get_temperature(self) -> float: ...
    def get_touch_sensors(self) -> dict: ...
    def get_sonar_data(self) -> dict: ...
    def is_obstacle_ahead(self, distance_threshold: float = 0.3) -> bool: ...

    # ====== Movimento ======
    def move_head(self, yaw: float = 0.0, pitch: float = 0.0, speed: float = 0.2) -> None: ...
    def move_arm(self, side: str = "R", shoulder_pitch: float = 0.0, shoulder_roll: float = 0.0,
                 elbow_yaw: float = 0.0, elbow_roll: float = 0.0,
                 wrist_yaw: float = 0.0, speed: float = 0.2) -> None: ...
    def open_hand(self, side: str = "R") -> None: ...
    def close_hand(self, side: str = "R") -> None: ...
    def go_to_posture(self, posture_name: str = "Stand", speed: float = 0.5) -> None: ...
    def move_to(self, x: float, y: float, theta: float) -> None: ...

    # ====== Movimento avançado ======
    def walk_to(self, x: float, y: float, theta: float = 0.0, speed: float = 0.5) -> bool: ...
    def walk_forward(self, distance: float, speed: float = 0.5) -> bool: ...
    def walk_backward(self, distance: float, speed: float = 0.5) -> bool: ...
    def turn_left(self, angle: float = 45.0, speed: float = 0.5) -> bool: ...
    def turn_right(self, angle: float = 45.0, speed: float = 0.5) -> bool: ...
    def strafe_left(self, distance: float, speed: float = 0.5) -> bool: ...
    def strafe_right(self, distance: float, speed: float = 0.5) -> bool: ...
